CREATE TABLE STUDENTS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
);

CREATE OR REPLACE PROCEDURE GET_STUDENT_DETAILS (
    P_ID IN INTEGER,
    P_NAME OUT VARCHAR,
    P_ADDRESS OUT VARCHAR
) 
AS
BEGIN
    SELECT
        NAME,
        ADDRESS
        INTO
        P_NAME,
        P_ADDRESS
    FROM
        STUDENTS
    WHERE
        ID = P_ID;
END;
